version: '3.9'

services:
  redis:
    image: redis:alpine3.18
    ports:
      - '6379:6379'
    command: [ "redis-server", "--port", "6379" ]
    networks:
      - backend
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
