version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "1321:1321"
    restart: unless-stopped
    networks:
      - backend
networks:
  backend:
    name: backend
    driver: bridge
