version: '3.9'

services:
  redis:
    image: redis:alpine3.18
    ports:
      - '6379:6379'
    command: [ "redis-server", "--port", "6379" ]
    networks:
      - backend

  app1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8881:8080"
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - backend
#    deploy:
#      resources:
#        limits:
#          cpus: '0.2'
#          memory: 500M

  app2:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8882:8080"
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - backend
#    deploy:
#      resources:
#        limits:
#          cpus: '0.2'
#          memory: 500M

  app3:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8883:8080"
    restart: unless-stopped
    networks:
      - backend
#    deploy:
#      resources:
#        limits:
#          cpus: '0.2'
#          memory: 500M

  ngnix-server:
    image: nginx:latest
    ports:
      - "1321:1321"
    volumes:
      - $PWD/cfg/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
